CREATE TABLE misc_stats(
  collected_date DATE, /* PRIMARY */
  team TEXT,           /* PRIMARY */
  age REAL,
  wins INT,
  losses INT,
  wins_pyth INT,
  losses_pyth INT,
  mov REAL,
  sos REAL,
  srs REAL,
  off_rtg REAL,
  def_rtg REAL,
  net_rtg REAL,
  pace REAL,
  fta_per_fga_pct REAL,
  fg3a_per_fga_pct REAL,
  ts_pct REAL,
  efg_pct REAL,
  tov_pct REAL,
  orb_pct REAL,
  ft_rate REAL,
  opp_efg_pct REAL,
  opp_tov_pct REAL,
  drb_pct REAL,
  opp_ft_rate REAL,
  arena_name TEXT,
  attendance INT,
  attendance_per_g INT,
  PRIMARY KEY (collected_date, team)
);