CREATE TABLE shooting_stats(
  collected_date DATE, /* PRIMARY */
  team TEXT,           /* PRIMARY */
  g INT,
  mp INT,
  fg_pct REAL,
  avg_dist REAL,
  fg2a_pct_fga REAL,
  pct_fga_00_03 REAL,
  pct_fga_03_10 REAL,
  pct_fga_10_16 REAL,
  pct_fga_16_xx REAL,
  fg3a_pct_fga REAL,
  fg2_pct REAL,
  fg_pct_00_03 REAL,
  fg_pct_03_10 REAL,
  fg_pct_10_16 REAL,
  fg_pct_16_xx REAL,
  fg3_pct REAL,
  fg2_pct_ast REAL,
  pct_fg2_dunk REAL,
  fg2_dunk INT,
  pct_fg2_layup REAL,
  fg2_layup INT,
  fg3_pct_ast REAL,
  pct_fg3a_corner REAL,
  fg3_pct_corner REAL,
  fg3a_heave INT,
  fg3_heave INT,
  opp_mp INT,
  opp_fg_pct REAL,
  opp_avg_dist REAL,
  opp_fg2a_pct_fga REAL,
  opp_pct_fga_00_03 REAL,
  opp_pct_fga_03_10 REAL,
  opp_pct_fga_10_16 REAL,
  opp_pct_fga_16_xx REAL,
  opp_fg3a_pct_fga REAL,
  opp_fg2_pct REAL,
  opp_fg_pct_00_03 REAL,
  opp_fg_pct_03_10 REAL,
  opp_fg_pct_10_16 REAL,
  opp_fg_pct_16_xx REAL,
  opp_fg3_pct REAL,
  opp_fg2_pct_ast REAL,
  opp_pct_fg2_dunk REAL,
  opp_fg2_dunk INT,
  opp_pct_fg2_layup REAL,
  opp_fg2_layup INT,
  opp_fg3_pct_ast REAL,
  opp_pct_fg3a_corner REAL,
  opp_fg3_pct_corner REAL,
  PRIMARY KEY (collected_date, team)
);