CREATE TABLE box_score(
  game_date DATE NOT NULL, /* PRIMARY */
  pid TEXT NOT NULL,       /* PRIMARY */
  starter BOOLEAN,
  team TEXT,
  mp TEXT,
  fg INT,
  fga INT,
  fg_pct REAL,
  fg3 INT,
  fg3a INT,
  fg3_pct REAL,
  ft INT,
  fta INT,
  ft_pct REAL,
  orb INT,
  drb INT,
  trb INT,
  ast INT,
  stl INT,
  blk INT,
  tov INT,
  pf INT,
  pts INT,
  plus_minus INT,
  ts_pct REAL,
  efg_pct REAL,
  fg3a_per_fga_pct REAL,
  fta_per_fga_pct REAL,
  orb_pct REAL,
  drb_pct REAL,
  trb_pct REAL,
  ast_pct REAL,
  stl_pct REAL,
  blk_pct REAL,
  tov_pct REAL,
  usg_pct REAL,
  off_rtg INT,
  def_rtg INT,
  reason TEXT,
  PRIMARY KEY (game_date, pid)
);

CREATE TABLE pbp
(
  id SERIAL NOT NULL,
  /* PRIMARY */
  game_date DATE NOT NULL,
  /* PRIMARY */
  assister TEXT,
  away_score INT,
  blocker TEXT,
  drebounder TEXT,
  distance INT,
  ejected TEXT,
  fg_type INT,
  foul_drawer TEXT,
  foul_type TEXT,
  fouler TEXT,
  full_timeout TEXT,
  home_score INT,
  make bool,
  orebounder TEXT,
  play TEXT,
  play_time REAL NOT NULL,
  play_time_raw TEXT NOT NULL,
  quarter INT,
  shooter TEXT,
  steal TEXT,
  sub_in TEXT,
  sub_out TEXT,
  turnover TEXT,
  turnover_type TEXT,
  violation TEXT,
  PRIMARY KEY (id, game_date)
);
