CREATE TABLE box_score(
  game_date DATE NOT NULL, /* PRIMARY */
  pid TEXT NOT NULL,       /* PRIMARY */
  starter BOOLEAN,
  team TEXT,
  mp TEXT,
  fg INT,
  fga INT,
  fg_pct REAL,
  fg3 INT,
  fg3a INT,
  fg3_pct REAL,
  ft INT,
  fta INT,
  ft_pct REAL,
  orb INT,
  drb INT,
  trb INT,
  ast INT,
  stl INT,
  blk INT,
  tov INT,
  pf INT,
  pts INT,
  plus_minus INT,
  ts_pct REAL,
  efg_pct REAL,
  fg3a_per_fga_pct REAL,
  fta_per_fga_pct REAL,
  orb_pct REAL,
  drb_pct REAL,
  trb_pct REAL,
  ast_pct REAL,
  stl_pct REAL,
  blk_pct REAL,
  tov_pct REAL,
  usg_pct REAL,
  off_rtg INT,
  def_rtg INT,
  reason TEXT,
  PRIMARY KEY (game_date, pid)
);