[
  {
    "id": string,
    "starter": bool,
    "team": string,
    "mp": string,
    "fg": int,
    "fga": int,
    "fg_pct": float,
    "fg3": int,
    "fg3a": int,
    "fg3_pct": float,
    "ft": int,
    "fta": int,
    "ft_pct": 1,
    "orb": int,
    "drb": int,
    "trb": int,
    "ast": int,
    "stl": int,
    "blk": int,
    "tov": int,
    "pf": int,
    "pts": int,
    "plus_minus": int,
    "ts_pct": float,
    "efg_pct": float,
    "fg3a_per_fga_pct": float,
    "fta_per_fga_pct": float,
    "orb_pct": float,
    "drb_pct": float,
    "trb_pct": float,
    "ast_pct": float,
    "stl_pct": float,
    "blk_pct": float,
    "tov_pct": float,
    "usg_pct": float,
    "off_rtg": int,
    "def_rtg": int,
    "reason": string,
  }
]