CREATE TABLE pbp(
  assister TEXT,
  away_score INT,
  blocker TEXT,
  drebounder TEXT,
  distance INT,
  ejected TEXT,
  foul_drawer TEXT,
  foul_type TEXT,
  fouler TEXT,
  full_timeout TEXT,
  home_score INT,
  make bool,
  orebounder TEXT,
  play TEXT,
  play_time INT, /* m:ss -> seconds */
  play_time_raw TEXT,
  quarter INT,
  shooter TEXT,
  steal TEXT,
  sub_in TEXT,
  sub_out TEXT,
  turnover TEXT,
  turnover_type TEXT,
  type INT,
  violation TEXT
);
