{
  "pid": string,
  "game_logs": [
    {
      "playoffs": bool,
      "game_season": int,
      "date": ???,
      "season": int,
      "age_years": int,
      "age_days": int,
      "team_id": string,
      "opp_id": string,
      "won": bool,
      "margin": int,
      "starter": bool,
      "minutes_played": int,
      "seconds_played": int,
      "fg": int,
      "fga": int,
      "fg_pct": float,
      "fg3": int,
      "fg3a": int,
      "fg3_pct": float,
      "ft": int,
      "fta": int,
      "ft_pct": float,
      "orb": int,
      "drb": int,
      "trb": int,
      "ast": int,
      "stl": int,
      "blk": int,
      "tov": int,
      "pf": int,
      "pts": int,
      "game_score": float,
      "plus_minus": int,
      "reason": string,
    }
  ],
  "first": string,
  "last": string,
  "feet": int,
  "inches": int,
  "lbs": int,
  "birth_year": int,
  "birth_month": int,
  "birth_day": int,
  "birth_city": string,
  "birth_state": string,
  "college_stats": [
    {
      "2010": {
        "age": int,
        "college": string,
        "g": int,
        "mp": int,
        "fg": int,
        "fga": int,
        "fg3": int,
        "fg3a": int,
        "ft": int,
        "fta": int,
        "orb": int,
        "trb": int,
        "ast": int,
        "stl": int,
        "blk": int,
        "tov": int,
        "pf": int,
        "pts": int,
        "fg_pct": float,
        "fg3_pct": float,
        "ft_pct": float,
        "mp_per_g": float,
        "pts_per_g": float,
        "trb_per_g": float,
        "ast_per_g": float,
      }
    }
  ],
  "twitter": string,
  "shoots": string,
  "position": int,
  "hs_city": string,
  "hs_state": string,
  "pick": int,
  "draft_year": int,
}